---
galaxy_info:
  author: rstyczynski
  description: Clone and manage GitHub repositories
  company: Personal
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: MacOSX
      versions:
        - all
  galaxy_tags:
    - github
    - git
    - clone
dependencies: []
