---
galaxy_info:
  author: rstyczynski
  description: Checkout or create Git branches with remote synchronization
  company: Personal
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: MacOSX
      versions:
        - all
  galaxy_tags:
    - github
    - git
    - branch
    - checkout
dependencies: []
