---
galaxy_info:
  author: rstyczynski
  description: Delete Git branches locally and remotely
  company: Personal
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: MacOSX
      versions:
        - all
  galaxy_tags:
    - github
    - git
    - branch
    - delete
dependencies: []
