---
galaxy_info:
  author: rstyczynski
  description: Commit changes to Git repository
  company: Personal
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: MacOSX
      versions:
        - all
  galaxy_tags:
    - github
    - git
    - repo
    - commit
dependencies: []
