---
galaxy_info:
  author: rstyczynski
  description: Push current branch to remote repository
  company: Personal
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: MacOSX
      versions:
        - all
  galaxy_tags:
    - github
    - git
    - branch
    - push
dependencies: []
