---
galaxy_info:
  author: rstyczynski
  description: Logout from GitHub CLI
  company: Personal
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: MacOSX
      versions:
        - all
  galaxy_tags:
    - github
    - git
    - auth
    - logout
dependencies: []
