---
galaxy_info:
  author: rstyczynski
  description: Check GitHub pull request status checks
  company: Personal
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: MacOSX
      versions:
        - all
  galaxy_tags:
    - github
    - git
    - pr
    - pullrequest
    - status
dependencies: []
